# Generated by Django 2.2 on 2019-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNo', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
